# This workflow will build jar files from this openapi project with Maven

name: OpenAPI-Build-Sample

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: 16
    - name: generate java client code
      run: npx @openapitools/openapi-generator-cli generate -i sample.yml -g java -o java_api_client
    - name: maven build
      run: mvn -B package --file pom.xml
      working-directory: ./java_api_client
    - name: upload war files
      uses: actions/upload-artifact@v2
      with:
        name: Jar files upload
        path: ./java_api_client/target/openapi*.jar
