# This workflow will build jar files from this openapi project with Maven

name: OpenAPI-Build-Sample

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install
        run: npm install
      - name: Test
        run: npm test      
# If you want to use self-hosted-runner, npm and maven must be installed in advance.
#    - name: Set up npm
#      run: apt install npm -y
#     - name: Set up maven
#      run: apt install maven -y
#    - name: set up openapi-generator-cli
#      run: npm install @openapitools/openapi-generator-cli
#    - name: generate java client code
#      run: npx openapi-generator-cli generate -i sample.yml -g java -o java_api_client
#    - name: maven build
#      run: mvn -B package --file pom.xml
#      working-directory: ./java_api_client
#    - name: upload war file
#      uses: actions/upload-artifact@v2
#      with:
#        name: mvn results
#        path: ./java_api_client/target/openapi*.jar
